name: Build frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
          
      - name: Build frontend
        run: npm run build
          
  push_frontend:
    runs-on: ubuntu-latest
    needs: [build_frontend]
    defaults:
      run:
        working-directory: ./frontend
    permissions:
      packages: write
    steps:
      - name: Set up checkout
        uses: actions/checkout@v2
      
      - name: Login to the GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/denisiomytnysiano/writeforme-frontend:${{ github.sha }
  
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  push_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  update_manifests:
    runs-on: ubuntu-latest
    needs: [push_frontend, push_backend]
    steps:
      - uses: actions/checkout@v2
