# This is a basic workflow to help you get started with Actions
name: Build pipeline

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  build_frontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          
      - name: Build frontend
        run: |
          npm run build
          
  push_frontend:
    runs-on: ubuntu-latest
    needs: [build_frontend]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      -
        name: Set up checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to the GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/frontend/.buildx-cache
          key: ${{ runner.os }}-buildx-db-restore-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-db-restore-
      -
        name: Build frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/denisiomytnysiano/writeforme-frontend:${{ github.sha }}
          cache-from: type=local,src=/tmp/frontend/.buildx-cache
          cache-to: type=local,dest=/tmp/frontend/.buildx-cache-new
      -
        name: Move cache
        run: |
          rm -rf /tmp/frontend/.buildx-cache
          mv /tmp/frontend/.buildx-cache-new /tmp/frontend/.buildx-cache
