name: Build frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
          
      - name: Build frontend
        run: npm run build
          
  push_frontend:
    runs-on: ubuntu-latest
    needs: [build_frontend]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Set up checkout
        uses: actions/checkout@v2
      
      - name: Login to the GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/denisiomytnysiano/writeforme-frontend:${{ github.sha }}
